# Generated by Django 6.1.1 on 2026-10-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('types', models.JSONField(default=list)),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
    ]
